spring:
  application:
    name: staff-management-auth-server
  jmx:
    default-domain: ${spring.application.name}
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true

server:
  port: 8060
  servlet:
    context-path: /${spring.application.name}
application:
  eureka-service:
    port: 8080
security:
  login:
    page: /login
    view: login
    default-success-url: /me
    failure-url: /login
  url:
    auth: /oauth/authorize,/oauth/confirm_access
  jwt:
    client-id: staffmanagementappService
    client-secret: staffmanagementapp@2024
    grant-types: password,authorization_code,refresh_token
    scopes: read,write,admin
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 86400
  signing-key:
    store-path: staffmanagemen.jks
    password: dawnbit@staffmanagemen@2024
    name: staff-management
